"""Recommendation Model - Track AI-Generated Suggestions

Captures every piece of advice the AI gives, enabling tracking and impact measurement.
Each recommendation can be accepted, rejected, or kept pending.
"""

from datetime import datetime
from typing import Optional
from enum import Enum
from sqlalchemy import String, ForeignKey, Numeric, func, DateTime, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import BaseModel


class RecommendationCategory(str, Enum):
    """Categories of recommendations the AI can make."""
    PRICING = "Pricing"
    STAFFING = "Staffing"
    WASTE = "Waste"
    INVENTORY = "Inventory"
    MENU = "Menu"
    PROMOTION = "Promotion"
    OPERATIONS = "Operations"


class RecommendationStatus(str, Enum):
    """Status of a recommendation."""
    PENDING = "Pending"
    ACCEPTED = "Accepted"
    REJECTED = "Rejected"


class Recommendation(BaseModel):
    """
    AI-generated recommendation for restaurant owner action.
    
    Attributes:
        id: Unique auto-incremented identifier
        tenant_id: Foreign key to parent tenant (restaurant)
        category: Type of recommendation (Pricing, Staffing, Waste, etc.)
        content: The AI's recommendation text (what should be done)
        impact_score: Predicted financial impact in dollars ($)
        status: Current status (Pending, Accepted, Rejected)
        applied_date: When the recommendation was acted upon (if Accepted)
        verified_impact: Actual measured impact after verification
        created_at: When the AI generated this recommendation
        updated_at: Last modification timestamp
    """
    
    __tablename__ = "recommendations"
    
    id: Mapped[int] = mapped_column(primary_key=True)
    
    tenant_id: Mapped[int] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True
    )
    
    # The actual recommendation text from AI
    content: Mapped[str] = mapped_column(String(2000), nullable=False)
    
    # Predicted financial impact ($)
    impact_score: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    
    # Current status of the recommendation
    status: Mapped[str] = mapped_column(
        String(20),
        default=RecommendationStatus.PENDING.value,
        nullable=False,
        index=True
    )
    
    # When the recommendation was acted upon
    applied_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    
    # Actual verified impact after implementation
    verified_impact: Mapped[Optional[float]] = mapped_column(
        Numeric(10, 2),
        nullable=True
    )
    
    # Verification report (generated by AI after measuring impact)
    verification_summary: Mapped[Optional[str]] = mapped_column(
        String(2000),
        nullable=True
    )
    
    # Relationship to tenant
    tenant = relationship("Tenant", back_populates="recommendations")
    
    # Check constraint: applied_date should only exist if status is Accepted
    __table_args__ = (
        CheckConstraint(
            "status != 'Accepted' OR applied_date IS NOT NULL",
            name="ck_applied_date_with_accepted"
        ),
    )
    
    def __repr__(self) -> str:
        return f"<Recommendation(id={self.id}, tenant_id={self.tenant_id}, category={self.category}, status={self.status})>"
    
    def __str__(self) -> str:
        return f"[{self.category}] {self.content[:60]}... (${self.impact_score} predicted)"
